### ISSUE TITLE
update import from hydrus.hydraspec to hydra_python_core

### ISSUE THREAD

**Issue by knakul853** [HTTP-APIs/hydra-flock-drone#17]
there is need to change all the imports from hydrus.hydraspec to  hydra_python_core  and include ```git+https://github.com/http-apis/hydra-python-core.git@(hash/version)#egg=hydra_python_core ```within the requirements.txt file

**Comment by Mec-iS** [comment]
@xadahiya is this fixed?

**Comment by xadahiya** [comment]
Yep. closing this
