### ISSUE TITLE
Update libraries

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydra-flock-drone#19]
We have vulnerabilities alerts for these libraries:

![Screenshot from 2019-04-02 11-25-24](https://user-images.githubusercontent.com/3146196/55395807-43795500-553a-11e9-91eb-2682c7a26343.png)

Requirements need to be updated to latest stable.

**Comment by de-sh** [comment]
Should we set it to use the latest version always. There is very low chance of there ever being a breaking change from flask without long enough prior notice.

**Comment by xadahiya** [comment]
I agree

**Comment by xadahiya** [comment]
Same goes for hydrus and everything else

**Comment by Mec-iS** [comment]
hydrus can use PyPi, core and parser still uses Github releases.
